namespace Xenon.Compiler.Semantics.Binding;

public enum BoundKind
{
    BlockStatement,
    VariableDeclarationStatement,
    ReturnStatement,
    ExpressionStatement,
    IfStatement,
    WhileStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,
    LiteralExpression,
    VariableExpression,
    ThisExpression,
    UnaryExpression,
    BinaryExpression,
    AssignmentExpression,
    CallExpression,
    MethodCallExpression,
    MemberAccessExpression,
    StaticFieldExpression,
    TypeLayoutExpression,
    InterfaceConversionExpression,
    ReferenceConversionExpression,
    ReferenceDereferenceExpression,
    InterfaceMethodCallExpression,
    IndexExpression,
    StructConstructionExpression,
    ConstructorCallExpression,
    BaseLifecycleCallExpression,
    ArrayCreationExpression,
    NewExpression,
    FreeExpression,
    ErrorExpression,
}
