<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>xenon</AssemblyName>
    <RootNamespace>Xenon.Cli</RootNamespace>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Xenon.CodeGen.LLVM/Xenon.CodeGen.LLVM.csproj" />
    <ProjectReference Include="../Xenon.Compiler/Xenon.Compiler.csproj" />
    <ProjectReference Include="../Xenon.Driver/Xenon.Driver.csproj" />
    <ProjectReference Include="../Xenon.ProjectSystem/Xenon.ProjectSystem.csproj" />
  </ItemGroup>
</Project>
