<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Xenon.CodeGen.LLVM</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLVMSharp" Version="$(LlvmSharpVersion)" />
    <PackageReference Include="libLLVM" Version="$(LlvmSharpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Xenon.Compiler/Xenon.Compiler.csproj" />
  </ItemGroup>
</Project>
