set(XENON_SUPPORTED_PLATFORMS darwin_arm64 win_x64 win_arm64)

function(xenon_platform_properties platform rid_var architecture_var generator_platform_var executable_var)
  if(platform STREQUAL "darwin_arm64")
    set(_rid osx-arm64)
    set(_architecture arm64)
    set(_generator_platform "")
    set(_executable Xenon.app/Contents/MacOS/xenon)
  elseif(platform STREQUAL "win_x64")
    set(_rid win-x64)
    set(_architecture x86_64)
    set(_generator_platform x64)
    set(_executable xenon.exe)
  elseif(platform STREQUAL "win_arm64")
    set(_rid win-arm64)
    set(_architecture arm64)
    set(_generator_platform ARM64)
    set(_executable xenon.exe)
  else()
    message(FATAL_ERROR "Unsupported Xenon build platform: ${platform}. Supported: ${XENON_SUPPORTED_PLATFORMS}")
  endif()
  set(${rid_var} "${_rid}" PARENT_SCOPE)
  set(${architecture_var} "${_architecture}" PARENT_SCOPE)
  set(${generator_platform_var} "${_generator_platform}" PARENT_SCOPE)
  set(${executable_var} "${_executable}" PARENT_SCOPE)
endfunction()

function(xenon_detect_platform output_var host_system host_processor generator_platform vs_platform)
  string(TOLOWER "${host_system}" _system)
  string(TOLOWER "${host_processor}" _processor)
  if(_system STREQUAL "windows")
    if(generator_platform)
      set(_architecture "${generator_platform}")
    elseif(vs_platform)
      set(_architecture "${vs_platform}")
    else()
      set(_architecture "${host_processor}")
    endif()
    string(TOLOWER "${_architecture}" _architecture)
    if(_architecture MATCHES "^(x64|amd64|x86_64)$")
      set(_platform win_x64)
    elseif(_architecture MATCHES "^(arm64|aarch64)$")
      set(_platform win_arm64)
    elseif(_architecture MATCHES "^(win32|x86|i[3-6]86)$")
      set(_platform windows_x86)
    else()
      set(_platform "windows_${_architecture}")
    endif()
  elseif(_system STREQUAL "darwin" AND _processor MATCHES "^(arm64|aarch64)$")
    set(_platform darwin_arm64)
  else()
    set(_platform "${_system}_${_processor}")
  endif()
  set(${output_var} "${_platform}" PARENT_SCOPE)
endfunction()
